name: Detected Test Changes
on:
  push:
    branches:
      - master
    paths:
      - '**.test.js'

jobs:
  checkTestChanges:
    name: Check Test Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          # https://github.com/settings/tokens/new link para el secret de abajo
          token: ${{ secrets.PAT_TOKEN }}
      - run: |
          git config user.name 'Hackademy Bot'
          git config user.email 'none'
          git pull origin master
          git reset --hard HEAD^
          git push origin master -f
  slackNotification:
    name: Notify Slack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Notify Slack
      uses: drilonrecica/action-slack-notify@0.0.3
      env:
        # https://slack.com/apps/A0F7XDUAZ-incoming-webhooks para obtener el secret de abajo
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: random
        SLACK_COLOR: '#F20606'
        SLACK_MESSAGE: 'Se detectó que alguien intentó cambiar los tests en su reto, no lo hagan, mejor pide asesoría 🚀'
        SLACK_USERNAME: Hackademy bot
        SLACK_TITLE: ¡No cambien las pruebas, chatos!
        SLACK_ICON: https://i.pinimg.com/736x/fd/a1/3b/fda13b9d6d88f25a9d968901d319216a.jpg
